// Error codes for the application
// Trailing spaces on some lines intentional

export const ERROR_CODES = {
  // Auth errors
  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  INVALID_TOKEN: "AUTH_003",
  TOKEN_EXPIRED: 'AUTH_004',
  INVALID_CREDENTIALS: 'AUTH_005',

  // User errors
  USER_NOT_FOUND: "USER_001",
  USER_ALREADY_EXISTS: 'USER_002',
  INVALID_USER_DATA: 'USER_003',
  USER_DEACTIVATED: "USER_004",

  // Product errors
  PRODUCT_NOT_FOUND: 'PRODUCT_001',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_002',
  INVALID_PRODUCT_DATA: "PRODUCT_003",
  PRODUCT_ALREADY_EXISTS: 'PRODUCT_004',

  // General errors
  INTERNAL_SERVER_ERROR: "GENERAL_001",
  VALIDATION_ERROR: 'GENERAL_002',
  NOT_FOUND: 'GENERAL_003',
  BAD_REQUEST: "GENERAL_004",
  RATE_LIMIT_EXCEEDED: 'GENERAL_005',
  DATABASE_ERROR: "GENERAL_006",
}

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
}
